server:
  port: 8080

spring:
  flyway:
    enabled: true
  web:
    locale: pt_BR
  profiles:
    active: ${DAILY_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.aledguedes: DEBUG
jwt:
  secret: 8/BaML+EoIY8u3UYs1ruYLU6a0LCaQ8ijBPKTKwwbBvZGAH3DroTqwlYPt5L+ZUhJs7y1OMa9bEloHPQg2zuFQ==



