spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dailybrief
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
